version: '3.1'

services:

  relational-db:
    image: postgres
    restart: always
    # networks:
    #   new:
    #     aliases:
    #       - database
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "143018h"
    ports:
      - "5436:5432"
    volumes:
      - relational-db:/var/lib/postgres

volumes:
  relational-db:
#   migrate:
#         image: migrate/migrate
#         networks:
#             - new
#         volumes:
#             - .:/migrations
#         command: ["-path", "/migrations", "-database",  "postgres://postgres:143018h@localhost:5432/postgres?sslmode=disable", "up", "1"]
#         links: 
#             - relational-db
#         depends_on:
#             - relational-db
# networks:
#       new:

#   migrate -path ./migrations -database 'postgres://postgres:143018h@localhost:5436/postgres?sslmode=disable' up
#   migrate -path ./migrations -database 'postgres://postgres:143018h@localhost:5436/postgres?sslmode=disable' down
#   